<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Kubanychbeks-MacBook-Pro.local" failures="1" tests="2" name="Standard user test" time="14.864" errors="0" timestamp="2020-08-15T15:04:29 EDT">
  <testcase classname="tests.LogInPageTest" name="verifyLogInStandardUser" time="3.588"/>
  <testcase classname="tests.LogInPageTest" name="verifyLockedUser" time="3.429">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Sorry, this user has been locked out..] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Sorry, this user has been locked out..] but found [Epic sadface: Sorry, this user has been locked out.]
at tests.LogInPageTest.verifyLockedUser(LogInPageTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLockedUser -->
  <testcase classname="tests.LogInPageTest" name="verifyTitle" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitle -->
</testsuite> <!-- Standard user test -->
